rm(list = ls())
library("stringr")
library("tuple")
library("rlang")
library("ggplot2")

load("funcoes/import.RData")
options(max.print=.Machine$integer.max)
Metrô <- ler("METROREC.csv")
erros <- conjura(Metrô)
resultado <- processa(erros)
